### ISSUE TITLE
Tag at last working version before cloud WIP?

### ISSUE THREAD

**Issue by sodabrew** [gonzojive/heatpump#21]
Hi! Would you consider tagging at commit 9ebf30fec97e28923677edec655ec6acea2a8839 as that appears to be the last stable commit before the recent work to add cloud service features.

I was able to install that revision with Go 1.19 easily:
```
go install \
    github.com/gonzojive/heatpump/cmd/cx34collector@9ebf30fec \
    github.com/gonzojive/heatpump/cmd/cx34install@9ebf30fec
```

However `@latest`, at this time, seems to require some additional effort to get building.

**Comment by gonzojive** [comment]
I think the only issue with @latest is that go.mod has a replace directive. https://github.com/gonzojive/heatpump/pull/22 should fix that and also has a CI check to make sure it doesn't recur.

I can release a new version once that is checked in.

**Comment by gonzojive** [comment]
```shell
go install github.com/gonzojive/heatpump/cmd/cx34collector@v0.0.4 github.com/gonzojive/heatpump/cmd/cx34install@v0.0.4
```

seems to work for me.

**Comment by gonzojive** [comment]
Please re-open if this feels unresolved.

**Comment by sodabrew** [comment]
Thank you! For completeness of the thread, there was one outstanding issue at 9ebf30fec, which was a duplicated line `scriptName` in the vars block in cx34install.go. Removed that locally and recompiled and I have a working copy.

I'll check out the newer tags as I have time! For now I'm working on setting up dual collection since I have two outdoor units.
